/* Ember Depths — original, dependency-free Canvas dungeon crawler. */
(() => {
'use strict';
const $ = id => document.getElementById(id), canvas = $('game'), ctx = canvas.getContext('2d');
const W=960,H=600, clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y), rand=(a,b)=>a+Math.random()*(b-a), pick=a=>a[Math.floor(Math.random()*a.length)];
const FLOORS=['The Mossbound Halls','The Sunken Crypt','The Violet Catacombs','The Cinder Vault','Throne of the Ember King'];
const COLORS=[['#192b24','#24392c','#86b179'],['#18292d','#263b41','#81b4bb'],['#251f32','#352b43','#b39fd4'],['#30231b','#443029','#de9c64'],['#302025','#472b2d','#edb06a']];
const WEAPONS=[
 {id:'iron',name:'Wayfarer’s Blade',type:'sword',damage:19,rate:.38,range:88,color:'#c9dac0',rarity:'Common',desc:'A faithful blade. Sweep through nearby enemies.'},
 {id:'spark',name:'Apprentice’s Spark',type:'staff',damage:17,rate:.45,range:600,color:'#88d9ca',rarity:'Common',desc:'A crystal focus that launches bolts of magic.'},
 {id:'ashbow',name:'Ashwood Bow',type:'bow',damage:23,rate:.48,range:700,color:'#d6c390',rarity:'Common',desc:'Quick arrows. Keep your distance and keep moving.'},
 {id:'frost',name:'Winter’s Fang',type:'sword',damage:28,rate:.36,range:96,color:'#9de9ee',rarity:'Rare',effect:'frost',desc:'Frost slows struck enemies for two seconds.'},
 {id:'ember',name:'Emberbrand',type:'sword',damage:36,rate:.42,range:105,color:'#ffab69',rarity:'Epic',effect:'burn',desc:'An ancient blade that sets its victims ablaze.'},
 {id:'void',name:'Starless Wand',type:'staff',damage:26,rate:.36,range:650,color:'#c3a3ff',rarity:'Rare',effect:'pierce',desc:'Void bolts pierce through multiple enemies.'},
 {id:'sun',name:'Dawncaller',type:'staff',damage:36,rate:.43,range:650,color:'#ffda8a',rarity:'Epic',effect:'burn',desc:'Throw condensed sunlight and burn the darkness.'},
 {id:'moon',name:'Moonstring',type:'bow',damage:32,rate:.38,range:700,color:'#a9cfff',rarity:'Rare',effect:'frost',desc:'Moonlit arrows chill and slow your prey.'},
 {id:'thorn',name:'Briarstorm',type:'bow',damage:23,rate:.44,range:600,color:'#a3df89',rarity:'Epic',effect:'triple',desc:'Launch three enchanted thorns with every shot.'},
 {id:'reaper',name:'Gravekeeper',type:'sword',damage:43,rate:.48,range:115,color:'#d4a7df',rarity:'Legendary',effect:'leech',desc:'A sweeping grave blade. Each hit restores 2 health.'},
 {id:'nova',name:'Novaheart',type:'staff',damage:44,rate:.34,range:700,color:'#ffce88',rarity:'Legendary',effect:'pierce',desc:'A fallen star. Its bolts pierce entire crowds.'},
 {id:'gale',name:'Gale of the Lost',type:'bow',damage:35,rate:.35,range:700,color:'#b9eaca',rarity:'Legendary',effect:'triple',desc:'Three spectral arrows answer every draw.'}
];
const RELICS=[
 {id:'ruby',name:'Bloodstone',desc:'+25 maximum health'},
 {id:'fang',name:'Wolf’s Tooth',desc:'+15% weapon damage'},
 {id:'feather',name:'Storm Feather',desc:'+12% movement speed'},
 {id:'coin',name:'Gilded Scarab',desc:'+35% gold from enemies'},
 {id:'shell',name:'Ironroot Shell',desc:'Take 20% less damage'},
 {id:'heart',name:'Kindled Heart',desc:'Heal 12 health when a room is cleared'}
];
const weapon=id=>WEAPONS.find(w=>w.id===id)||WEAPONS[0];
let run=null,mode='title',selected='knight',last=0,elapsed=0,saving=0,toastTime=0,shake=0,aim={x:1,y:0},mouseAim=false,stick={x:0,y:0},attacking=false,keys=new Set(),projectiles=[],fx=[],texts=[],swing=null,audioCtx=null,sound=false;
let best=0;try{best=Number(localStorage.getItem('ember-best'))||0;}catch{}
const icons={sword:'⚔',staff:'✦',bow:'➶'};
function beep(f=300,d=.08,type='sine',vol=.025){if(!sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(f,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(f*.5,audioCtx.currentTime+d);g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d);}catch{}}
function toast(t){$('toast').textContent=t;$('toast').classList.add('visible');toastTime=3;}
function modal(html,state){mode=state;keys.clear();stick={x:0,y:0};$('stick-thumb').style.transform='';attacking=false;$('hint').textContent='';$('overlay').classList.remove('hidden');$('modal').innerHTML=html;const first=$('modal').querySelector('button');if(first)first.focus();}
function resume(){if(!run)return;mode='play';$('overlay').classList.add('hidden');canvas.focus();}
function savedRun(){try{let r=JSON.parse(localStorage.getItem('ember-run'));if(r?.version===1&&r.player?.hp>0&&Array.isArray(r.rooms)&&r.rooms.length===9&&r.floor>=1&&r.floor<=5)return r;}catch{}return null;}
function save(){if(!run||run.player.hp<=0||mode==='win')return;try{localStorage.setItem('ember-run',JSON.stringify(run));}catch{}}
function clearSave(){try{localStorage.removeItem('ember-run');}catch{}}
function title(){const saved=savedRun();modal(`<div class="eyebrow">AN EXPEDITION INTO THE UNKNOWN</div><h1>Ember Depths</h1><p>Five floors below the forgotten keep, a king still burns.<br>Find strange relics. Forge your build. Make it out alive.</p><div class="classes">${[['knight','⚔','Knight','Blade · 120 health'],['mage','✦','Mage','Magic · 90 health'],['ranger','➶','Ranger','Bow · 100 health']].map(([id,i,n,d])=>`<button class="class-card ${selected===id?'active':''}" data-class="${id}"><span>${i}</span><strong>${n}</strong><small>${d}</small></button>`).join('')}</div><div class="modal-actions"><button class="primary" id="start">Begin descent</button>${saved?'<button id="continue">Continue run</button>':''}</div><p>Clear rooms to unlock doors. Stand near objects and press E or USE.<br>Find the guardian in the bottom-right room of each floor.</p>`,'title');
 document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{selected=b.dataset.class;title();});$('start').onclick=()=>start(selected);if(saved)$('continue').onclick=()=>{run=saved;projectiles=[];fx=[];texts=[];sync();if(run.pendingBlessing||run.player.xp>=run.player.nextXP)levelUp();else resume();};
}
function start(cls){const max=cls==='knight'?120:cls==='mage'?90:100;run={version:1,class:cls,floor:1,room:0,rooms:[],gold:0,kills:0,relics:[],inventory:[cls==='knight'?'iron':cls==='mage'?'spark':'ashbow'],weapon:cls==='knight'?'iron':cls==='mage'?'spark':'ashbow',player:{x:130,y:300,hp:max,maxHP:max,level:1,xp:0,nextXP:65,damageBonus:0,speedBonus:0,haste:0,potions:3,invuln:0,attackCD:0,dashCD:0,dashTime:0,dx:1,dy:0},time:0};newFloor();resume();save();beep(520,.15);}
function makeEnemy(type,x,y){const f=run.floor,boss=type==='boss',hp=boss?200+f*100:26+f*12+(type==='skeleton'?12:type==='wraith'?8:0);return{type,x,y,r:boss?30:type==='slime'?15:13,hp,maxHP:hp,cd:rand(.4,1.8),slow:0,burn:0,burnTick:0,flash:0,wind:0,charge:0,ax:0,ay:0};}
function newFloor(){run.rooms=[];for(let i=0;i<9;i++){const start=i===0,shop=i===4,boss=i===8;const obstacles=start||shop||boss?[]:pick([[{x:300,y:220,r:30},{x:660,y:380,r:30}],[{x:340,y:180,r:27},{x:620,y:180,r:27},{x:340,y:420,r:27},{x:620,y:420,r:27}],[{x:480,y:300,r:36}]]);const enemies=[];if(!start&&!shop){const count=boss?1:3+run.floor+Math.floor(Math.random()*2);for(let j=0;j<count;j++){let point;for(let tries=0;tries<100;tries++){point={x:rand(270,730),y:rand(130,470)};if(!obstacles.some(o=>dist(point,o)<o.r+55))break;}enemies.push(makeEnemy(boss?'boss':pick(run.floor===1?['slime','skeleton','archer']:['slime','skeleton','archer','wraith']),point.x,point.y));}if(boss){enemies[0].x=680;enemies[0].y=300;}}
 const rare=WEAPONS.filter(w=>w.rarity!=='Common'&&(run.floor>=3||w.rarity!=='Legendary'));run.rooms.push({visited:false,cleared:start||shop,enemies,obstacles,chest:!start&&!shop&&!boss?{x:480,y:150,opened:false}:null,shop,shopWeapon:pick(rare).id,stock:{flask:true,weapon:true,relic:true},shopRelic:pick(RELICS).id,portal:boss,trap:(!start&&!shop&&!boss&&run.floor>1)?{x:480,y:430,phase:rand(0,3),cd:0}:null,seed:Math.floor(rand(1,100000))});}
 run.room=0;run.player.x=140;run.player.y=300;run.player.invuln=1;projectiles=[];fx=[];texts=[];run.rooms[0].visited=true;sync();toast(FLOORS[run.floor-1]);}
const room=()=>run?.rooms[run.room];
function damageValue(){return Math.round(weapon(run.weapon).damage*(1+run.player.damageBonus+(run.relics.includes('fang')?.15:0)));}
function sync(){if(!run){$('best').textContent=`BEST DEPTH ${best||'—'}`;return;}const p=run.player,w=weapon(run.weapon);$('hp-label').textContent=`${Math.ceil(p.hp)} / ${p.maxHP}`;$('hp-bar').style.width=`${clamp(p.hp/p.maxHP*100,0,100)}%`;$('xp-bar').style.width=`${clamp(p.xp/p.nextXP*100,0,100)}%`;$('floor').textContent=`0${run.floor} / 05`;$('level').textContent=String(p.level).padStart(2,'0');$('gold').textContent=run.gold;$('potions').textContent=p.potions;$('class-label').textContent=run.class;$('weapon-icon').textContent=icons[w.type];$('weapon-name').textContent=w.name;$('weapon-desc').textContent=w.desc;$('damage').textContent=`${damageValue()} damage`;$('rarity').textContent=w.rarity;$('room-label').textContent=FLOORS[run.floor-1].toUpperCase();$('room-count').textContent=`${run.rooms.filter(r=>r.visited).length} / 9`;$('minimap').innerHTML=run.rooms.map((r,i)=>`<div class="map-room ${r.visited?'visited':''} ${i===run.room?'current':''}">${i===run.room?'◆':i===8?'♜':i===4?'$':r.cleared&&r.visited?'·':''}</div>`).join('');$('relics').innerHTML=run.relics.length?run.relics.map(id=>{const r=RELICS.find(r=>r.id===id);return `<span class="relic-pill" title="${r.desc}">◆ ${r.name}</span>`;}).join(''):'<p>No relics discovered.</p>';$('best').textContent=`BEST DEPTH ${Math.max(best,run.floor)} / 5`;}
function blocked(x,y,r){return x<50+r||x>W-50-r||y<65+r||y>H-50-r||room().obstacles.some(o=>Math.hypot(x-o.x,y-o.y)<r+o.r);}
function move(e,dx,dy,dt){const x=e.x+dx*dt,y=e.y+dy*dt;if(!blocked(x,e.y,e.r||13))e.x=x;if(!blocked(e.x,y,e.r||13))e.y=y;}
function particles(x,y,color,n=9){for(let i=0;i<n;i++)fx.push({x,y,vx:rand(-130,130),vy:rand(-130,130),life:rand(.2,.55),color});}
function float(x,y,value,color='#f4dfb3'){texts.push({x,y,value:String(value),color,life:.8});}
function hurtPlayer(amount){const p=run.player;if(p.invuln>0)return;p.hp-=Math.ceil(amount*(run.relics.includes('shell')?.8:1));p.invuln=.65;shake=7;particles(p.x,p.y,'#ff7773');beep(110,.12,'sawtooth');sync();if(p.hp<=0){p.hp=0;die();}}
function hitEnemy(e,amount,w){if(e.hp<=0)return;e.hp-=amount;e.flash=.12;float(e.x,e.y-22,amount);particles(e.x,e.y,w?.color||'#b5d389',5);if(w?.effect==='frost')e.slow=2;if(w?.effect==='burn')e.burn=3;if(w?.effect==='leech')run.player.hp=Math.min(run.player.maxHP,run.player.hp+2);if(e.hp<=0){run.kills++;run.gold+=Math.ceil(rand(4,9)*run.floor*(run.relics.includes('coin')?1.35:1));run.player.xp+=e.type==='boss'?85+run.floor*25:12+run.floor*3;particles(e.x,e.y,'#d7ba72',13);if(Math.random()<.08)run.player.potions++;checkClear();sync();}}
function checkClear(){const r=room();if(r.cleared||r.enemies.some(e=>e.hp>0))return;r.cleared=true;if(run.relics.includes('heart'))run.player.hp=Math.min(run.player.maxHP,run.player.hp+12);beep(700,.2,'triangle');toast(r.portal?'Guardian defeated. The stairway is open.':'Room cleared. Doors unlocked.');save();}
function shoot(x,y,angle,w,enemy=false,extra={}){projectiles.push({x,y,vx:Math.cos(angle)*(enemy?220:w.type==='bow'?600:460),vy:Math.sin(angle)*(enemy?220:w.type==='bow'?600:460),life:enemy?4:w.range/(w.type==='bow'?600:460),enemy,damage:enemy?10+run.floor*3:damageValue(),color:enemy?'#ed8b83':w.color,weapon:w?.id,hits:[],...extra});}
function attack(){if(mode!=='play')return;const p=run.player,w=weapon(run.weapon);if(p.attackCD>0)return;p.attackCD=w.rate/(1+p.haste);let a=Math.atan2(aim.y,aim.x);if(!mouseAim){const nearest=room().enemies.filter(e=>e.hp>0).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(nearest)a=Math.atan2(nearest.y-p.y,nearest.x-p.x);}p.dx=Math.cos(a);p.dy=Math.sin(a);if(w.type==='sword'){swing={x:p.x,y:p.y,a,life:.17,color:w.color,range:w.range};for(const e of room().enemies){const da=Math.atan2(Math.sin(Math.atan2(e.y-p.y,e.x-p.x)-a),Math.cos(Math.atan2(e.y-p.y,e.x-p.x)-a));if(dist(e,p)<w.range+e.r&&Math.abs(da)<1.3)hitEnemy(e,damageValue(),w);}beep(220,.06,'triangle');}else{shoot(p.x+p.dx*20,p.y+p.dy*20,a,w);if(w.effect==='triple'){shoot(p.x,p.y,a-.18,w);shoot(p.x,p.y,a+.18,w);}beep(w.type==='staff'?550:350,.07,'triangle');}}
function dash(){if(mode!=='play')return;let p=run.player;if(p.dashCD>0)return;const mx=stick.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),my=stick.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(Math.hypot(mx,my)>.1){const n=Math.hypot(mx,my);p.dx=mx/n;p.dy=my/n;}p.dashTime=.17;p.dashCD=1.3;p.invuln=.25;particles(p.x,p.y,'#a9e0c1',8);beep(420,.07);}
function heal(){if(mode!=='play')return;const p=run.player;if(p.potions<=0){toast('No healing flasks left. Find a merchant.');return;}if(p.hp>=p.maxHP){toast('Your vitality is full.');return;}p.potions--;p.hp=Math.min(p.maxHP,p.hp+55);particles(p.x,p.y,'#a5f39e',16);toast('Restored 55 vitality');beep(800,.15);sync();save();}
function interactables(){const r=room(),i=run.room,objects=[];if(r.cleared){if(i%3>0)objects.push({x:67,y:300,type:'door',next:i-1,spawn:{x:855,y:300}});if(i%3<2)objects.push({x:893,y:300,type:'door',next:i+1,spawn:{x:105,y:300}});if(i>=3)objects.push({x:480,y:83,type:'door',next:i-3,spawn:{x:480,y:515}});if(i<6)objects.push({x:480,y:533,type:'door',next:i+3,spawn:{x:480,y:105}});if(r.chest&&!r.chest.opened)objects.push({...r.chest,type:'chest'});if(r.shop)objects.push({x:480,y:300,type:'shop'});if(r.portal)objects.push({x:680,y:300,type:'portal'});}return objects;}
function nearby(){return interactables().find(o=>dist(o,run.player)<(o.type==='door'?75:80));}
function interact(){if(mode!=='play')return;const o=nearby();if(!o){toast(room().cleared?'Stand near a door, chest, or merchant.':'Clear the room to unlock its doors.');return;}if(o.type==='door'){run.room=o.next;Object.assign(run.player,o.spawn);run.player.invuln=.8;room().visited=true;projectiles=[];swing=null;sync();save();}if(o.type==='chest'){room().chest.opened=true;run.gold+=15+run.floor*8;const available=RELICS.filter(r=>!run.relics.includes(r.id));if(Math.random()<.35&&available.length){addRelic(pick(available).id);}else{const pool=WEAPONS.filter(w=>w.rarity!=='Common'&&(run.floor>=3||w.rarity!=='Legendary')&&!run.inventory.includes(w.id));if(pool.length){const w=pick(pool);run.inventory.push(w.id);lootModal(w);}else{run.player.potions++;toast('Treasure: gold and a healing flask');}}beep(750,.15);sync();save();}if(o.type==='shop')shop();if(o.type==='portal'){if(run.floor===5)win();else{run.floor++;run.player.hp=Math.min(run.player.maxHP,run.player.hp+30);run.player.potions++;best=Math.max(best,run.floor);try{localStorage.setItem('ember-best',best);}catch{}newFloor();save();}}}
function lootModal(w){modal(`<div class="eyebrow">${w.rarity.toUpperCase()} WEAPON FOUND</div><h2>${w.name}</h2><p>${w.desc}<br>${w.damage} base damage · ${w.type}</p><div class="modal-actions"><button id="equip-loot" class="primary">Equip weapon</button><button id="keep-loot">Keep in pack</button></div>`,'loot');$('equip-loot').onclick=()=>{run.weapon=w.id;sync();save();resume();};$('keep-loot').onclick=resume;}
function addRelic(id){if(run.relics.includes(id)){run.gold+=30;toast('Duplicate relic traded for 30 gold');return;}run.relics.push(id);if(id==='ruby'){run.player.maxHP+=25;run.player.hp+=25;}const r=RELICS.find(r=>r.id===id);toast(`${r.name}: ${r.desc}`);sync();save();}
function shop(){const r=room(),w=weapon(r.shopWeapon),relic=RELICS.find(a=>a.id===r.shopRelic),cost=65+run.floor*20,rcost=55+run.floor*15;modal(`<div class="eyebrow">A FRIEND IN THE DARK</div><h2>The Lantern Merchant</h2><p>“Even down here, a little gold opens doors.”<br>You have ${run.gold} gold.</p><div class="shop-list"><button id="buy-flask" ${!r.stock.flask||run.gold<25?'disabled':''}><span>Healing flask<small>Restores 55 vitality · one per floor</small></span><b>25 G</b></button><button id="buy-weapon" ${!r.stock.weapon||run.gold<cost?'disabled':''}><span>${w.name}<small>${w.rarity} · ${w.damage} damage</small></span><b>${cost} G</b></button><button id="buy-relic" ${!r.stock.relic||run.gold<rcost?'disabled':''}><span>${relic.name}<small>${relic.desc}</small></span><b>${rcost} G</b></button></div><button id="leave-shop">Return to dungeon</button>`,'shop');$('buy-flask').onclick=()=>{run.gold-=25;run.player.potions++;r.stock.flask=false;sync();save();shop();};$('buy-weapon').onclick=()=>{run.gold-=cost;r.stock.weapon=false;if(!run.inventory.includes(w.id))run.inventory.push(w.id);sync();save();lootModal(w);};$('buy-relic').onclick=()=>{run.gold-=rcost;r.stock.relic=false;addRelic(relic.id);shop();};$('leave-shop').onclick=resume;}
function levelUp(){const p=run.player;if(!run.pendingBlessing){p.xp-=p.nextXP;p.level++;p.nextXP=Math.round(p.nextXP*1.38);p.hp=Math.min(p.maxHP,p.hp+20);run.pendingBlessing=true;}modal(`<div class="eyebrow">LEVEL ${p.level}</div><h2>Your power grows</h2><p>Choose a blessing for this expedition. Restored 20 vitality.</p><div class="choices"><button class="choice" data-up="might"><b>Sharpened will</b><small>+20% base weapon damage</small></button><button class="choice" data-up="vitality"><b>Deep roots</b><small>+25 max health, heal 25</small></button><button class="choice" data-up="haste"><b>Quickening</b><small>+15% attack speed, +5% movement speed</small></button></div>`,'level');document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{if(b.dataset.up==='might')p.damageBonus+=.2;if(b.dataset.up==='vitality'){p.maxHP+=25;p.hp=Math.min(p.maxHP,p.hp+25);}if(b.dataset.up==='haste'){p.haste+=.15;p.speedBonus+=.05;}run.pendingBlessing=false;sync();save();if(p.xp>=p.nextXP)levelUp();else resume();});sync();save();}
function gear(){if(!run||['title','dead','win','level','loot'].includes(mode))return;modal(`<div class="eyebrow">YOUR EQUIPMENT</div><h2>The wayfarer’s pack</h2><p>Equip any weapon you’ve found. Your class doesn’t limit your gear.</p><div class="gear-list">${run.inventory.map(id=>{const w=weapon(id);return `<div class="gear-row"><span>${icons[w.type]}</span><div><b>${w.name}</b><small>${w.rarity} · ${w.damage} base damage</small></div><button data-equip="${id}" ${run.weapon===id?'disabled':''}>${run.weapon===id?'Equipped':'Equip'}</button></div>`;}).join('')}</div><button id="close-gear">Return to dungeon</button>`,'gear');document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{run.weapon=b.dataset.equip;sync();save();gear();});$('close-gear').onclick=resume;}
function pause(){if(mode==='play'){save();modal('<div class="eyebrow">TAKE A BREATH</div><h2>Expedition paused</h2><p>Your progress is saved in this browser.</p><div class="modal-actions"><button id="resume" class="primary">Resume</button><button id="menu">Main menu</button></div>','pause');$('resume').onclick=resume;$('menu').onclick=title;}else if(['pause','gear','shop'].includes(mode))resume();}
function endStats(){return `<p>Depth ${run.floor} / 5 · Level ${run.player.level} · ${run.kills} enemies defeated<br>${run.relics.length} relics found · ${Math.floor(run.time/60)}m ${Math.floor(run.time%60)}s survived</p>`;}
function die(){clearSave();best=Math.max(best,run.floor);try{localStorage.setItem('ember-best',best);}catch{}sync();modal(`<div class="eyebrow">THE DEPTHS REMEMBER</div><h1>Your flame fades</h1>${endStats()}<div class="modal-actions"><button id="retry" class="primary">Try another descent</button><button id="to-title">Choose a new path</button></div>`,'dead');$('retry').onclick=()=>start(run.class);$('to-title').onclick=title;}
function win(){clearSave();best=5;try{localStorage.setItem('ember-best',5);}catch{}modal(`<div class="eyebrow">THE EMBER KING HAS FALLEN</div><h1>You carry the dawn</h1><p>The old king’s fire is finally quiet. Beyond the broken keep,<br>the world is waking up.</p>${endStats()}<button id="again" class="primary">Begin a new expedition</button>`,'win');$('again').onclick=title;beep(1000,.5,'triangle');}
function update(dt){if(mode!=='play'||!run)return;run.time+=dt;const p=run.player,r=room();p.invuln=Math.max(0,p.invuln-dt);p.attackCD=Math.max(0,p.attackCD-dt);p.dashCD=Math.max(0,p.dashCD-dt);p.dashTime=Math.max(0,p.dashTime-dt);let mx=stick.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),my=stick.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);const n=Math.hypot(mx,my);if(p.dashTime>0){move(p,p.dx*710,p.dy*710,dt);}else if(n>.08){mx/=Math.max(n,1);my/=Math.max(n,1);const speed=205*(1+p.speedBonus+(run.relics.includes('feather')?.12:0));move(p,mx*speed,my*speed,dt);if(!mouseAim){aim={x:mx,y:my};p.dx=mx;p.dy=my;}}
 if(attacking||keys.has(' ')||keys.has('j'))attack();
 for(const e of r.enemies){if(e.hp<=0)continue;e.cd-=dt;e.slow=Math.max(0,e.slow-dt);e.flash=Math.max(0,e.flash-dt);e.burn=Math.max(0,e.burn-dt);if(e.burn>0){e.burnTick-=dt;if(e.burnTick<=0){e.burnTick=.5;hitEnemy(e,5);}}if(e.hp<=0)continue;const d=dist(e,p),a=Math.atan2(p.y-e.y,p.x-e.x),speed=(e.type==='slime'?60:e.type==='wraith'?120:e.type==='boss'?65:85)*(e.slow>0?.4:1);
 if(e.type==='archer'){if(d>340)move(e,Math.cos(a)*speed,Math.sin(a)*speed,dt);if(d<185)move(e,-Math.cos(a)*speed,-Math.sin(a)*speed,dt);if(e.cd<=0){shoot(e.x,e.y,a,null,true);e.cd=1.6;}}
 else if(e.type==='boss'){if(e.charge>0){e.charge-=dt;move(e,e.ax*440,e.ay*440,dt);}else if(e.wind>0){e.wind-=dt;if(e.wind<=0)e.charge=.5;}else{move(e,Math.cos(a)*speed,Math.sin(a)*speed,dt);if(e.cd<=0){if(Math.random()<.5){e.wind=.75;e.ax=Math.cos(a);e.ay=Math.sin(a);e.cd=3;}else{const count=8+run.floor;for(let j=0;j<count;j++)shoot(e.x,e.y,a+j*Math.PI*2/count,null,true);e.cd=2.4;}}}}
 else move(e,Math.cos(a)*speed,Math.sin(a)*speed,dt);
 if(dist(e,p)<e.r+14)hurtPlayer(e.type==='boss'?22+run.floor*3:8+run.floor*3);if(mode!=='play')return;}
 for(let i=projectiles.length-1;i>=0;i--){const b=projectiles[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(blocked(b.x,b.y,3)){projectiles.splice(i,1);continue;}if(b.enemy){if(dist(b,p)<18){hurtPlayer(b.damage);b.life=0;}}else{for(let j=0;j<r.enemies.length;j++){const e=r.enemies[j];if(e.hp>0&&!b.hits.includes(j)&&dist(b,e)<e.r+7){hitEnemy(e,b.damage,weapon(b.weapon));b.hits.push(j);if(weapon(b.weapon).effect!=='pierce'){b.life=0;break;}}}}if(b.life<=0)projectiles.splice(i,1);if(mode!=='play')return;}
 if(r.trap){r.trap.phase=(r.trap.phase+dt)%3.5;r.trap.cd=Math.max(0,r.trap.cd-dt);if(r.trap.phase>2.7&&dist(r.trap,p)<45&&r.trap.cd<=0){hurtPlayer(12+run.floor*2);r.trap.cd=.8;}}
 if(mode!=='play')return;if(p.xp>=p.nextXP){levelUp();return;}const o=nearby();$('hint').textContent=o?`E / USE · ${o.type==='door'?'Enter next room':o.type==='chest'?'Open treasure':o.type==='shop'?'Talk to merchant':run.floor===5?'Leave the depths':'Descend · heal 30 vitality'}`:'';saving+=dt;if(saving>4){saving=0;save();}syncVitals();}
function syncVitals(){const p=run.player;$('hp-label').textContent=`${Math.ceil(p.hp)} / ${p.maxHP}`;$('hp-bar').style.width=`${clamp(p.hp/p.maxHP*100,0,100)}%`;}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}
function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function seeded(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
function drawRoom(r,f=1){const palette=COLORS[f-1],rng=seeded(r?.seed||125);rect(0,0,W,H,'#0b110e');rect(48,64,864,488,palette[0]);for(let y=64;y<552;y+=40){for(let x=48;x<912;x+=48){rect(x+1,y+1,46,38,rng()>.65?palette[1]:palette[0]);if(rng()<.2){rect(x+7,y+12,12,2,'#364435');rect(x+15,y+14,2,7,'#364435');}if(rng()<.13){rect(x+27,y+24,4,3,palette[2]+'50');}}}for(let y=0;y<H;y+=32)for(let x=0;x<W;x+=48){if(x<48||x>=912||y<64||y>=552){rect(x+1,y+1,46,30,'#29362c');rect(x+2,y+2,44,4,'#3d4b37');rect(x+2,y+27,44,4,'#18221b');}}
 const i=run?.room||0;[[i%3>0,25,264,38,72],[i%3<2,898,264,38,72],[i>=3,444,35,72,38],[i<6,444,533,72,38]].forEach(([exists,x,y,w,h])=>{if(!exists)return;rect(x,y,w,h,'#060d09');rect(x+3,y+3,w-6,h-6,'#18251d');if(!r?.cleared){for(let j=0;j<(w>h?w:h);j+=12)rect(w>h?x+j:x,w>h?y:y+j,w>h?4:w,w>h?h:4,'#785e45');}else{rect(x+5,y+5,w-10,h-10,'#477453');rect(x+9,y+9,w-18,h-18,'#101d15');}});
 for(const [x,y] of [[100,90],[860,90],[100,510],[860,510]]){const g=ctx.createRadialGradient(x,y,1,x,y,100);g.addColorStop(0,'#ebb25b33');g.addColorStop(1,'#eaa43c00');ctx.fillStyle=g;ctx.fillRect(x-100,y-100,200,200);rect(x-6,y+3,12,14,'#3d3021');circle(x,y-3,7+Math.sin(elapsed*7+x)*2,'#ffd08b');circle(x,y-5,3,'#fff1b4');}
 if(r){for(const o of r.obstacles){circle(o.x+5,o.y+10,o.r+6,'#080d0b77');rect(o.x-o.r,o.y-o.r,o.r*2,o.r*2,'#42513c');rect(o.x-o.r+5,o.y-o.r+5,o.r*2-10,o.r*2-10,'#2d3e2d');rect(o.x-o.r,o.y-o.r,o.r*2,6,'#647255');rect(o.x-o.r,o.y+o.r-5,o.r*2,7,'#172319');}if(r.trap){const t=r.trap;circle(t.x,t.y,40,t.phase>2.7?'#ed996066':t.phase>2?'#db664333':'#354237');for(let j=-2;j<=2;j++)rect(t.x+j*12-3,t.y-3,6,t.phase>2.7?22:6,t.phase>2.7?'#e5bd98':'#74816a');}
 if(r.chest){const c=r.chest;circle(c.x,c.y+12,24,'#070d0988');rect(c.x-21,c.y-13,42,28,c.opened?'#42382a':'#987443');rect(c.x-22,c.y-18,44,10,c.opened?'#574b36':'#b99252');rect(c.x-3,c.y-12,6,23,'#e2c582');if(!c.opened){rect(c.x-6,c.y-4,12,9,'#e7c574');circle(c.x,c.y-28,2+Math.sin(elapsed*3),'#ffe49b');}}
 if(r.shop){circle(480,320,27,'#0a120ba0');rect(459,280,42,35,'#7a587e');rect(465,267,30,27,'#b79272');rect(463,264,34,9,'#433951');rect(470,277,4,4,'#171d16');rect(487,277,4,4,'#171d16');rect(450,309,61,15,'#56402c');circle(530,286,11,'#ffc577');ctx.fillStyle='#d9c792';ctx.font='14px Georgia';ctx.textAlign='center';ctx.fillText('MERCHANT',480,250);}
 if(r.portal&&r.cleared){for(let j=0;j<5;j++)rect(646+j*4,280+j*9,68-j*8,8,'#647054');circle(680,298,42+Math.sin(elapsed*3)*3,'#eeb06b33');ctx.strokeStyle='#d9b179';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(680,300,46,35,0,0,Math.PI*2);ctx.stroke();}}
}
function drawEnemy(e){if(e.hp<=0)return;let x=e.x,y=e.y+Math.sin(elapsed*4+e.x)*2;circle(x,y+e.r*.8,e.r,'#0005');if(e.wind>0){ctx.strokeStyle='#ffaf63aa';ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+e.ax*220,y+e.ay*220);ctx.stroke();circle(x,y,40,'#ef985344');}
 if(e.type==='slime'){circle(x,y+3,16,e.flash?'#fff2bf':'#7da779');rect(x-14,y+2,28,11,e.flash?'#fff2bf':'#6b9467');rect(x-8,y-3,4,5,'#142b20');rect(x+4,y-3,4,5,'#142b20');rect(x-6,y-10,6,3,'#bad092');}
 else if(e.type==='boss'){rect(x-25,y-5,50,41,e.flash?'#ffeac0':'#6c3c38');rect(x-20,y-26,40,35,e.flash?'#fff':'#b39b7c');rect(x-24,y-30,48,10,'#dab36f');for(let i=-2;i<=2;i++)rect(x+i*10-3,y-39,6,14,'#dab36f');rect(x-13,y-12,8,6,'#ff875a');rect(x+5,y-12,8,6,'#ff875a');rect(x-42,y-5,12,58,'#ad865f');rect(x-47,y-14,23,21,'#e4ad73');}
 else if(e.type==='wraith'){circle(x,y-10,14,e.flash?'#fff':'#a295cc');rect(x-14,y-8,28,30,'#756997');for(let j=-1;j<=1;j++)rect(x+j*9-4,y+17,7,9+Math.sin(elapsed*8+j)*4,'#8e80b5');rect(x-7,y-12,4,5,'#e6e0ff');rect(x+3,y-12,4,5,'#e6e0ff');}
 else{const c=e.flash?'#fff':'#c8c3a3';rect(x-9,y-21,18,17,c);rect(x-7,y-1,14,20,c);rect(x-13,y+1,26,5,c);rect(x-8,y+20,5,12,c);rect(x+3,y+20,5,12,c);rect(x-6,y-16,4,5,'#252c23');rect(x+2,y-16,4,5,'#252c23');rect(x-4,y+4,8,9,'#5e6652');if(e.type==='archer'){ctx.strokeStyle='#b78c5d';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x+15,y+8,18,-1.3,1.3);ctx.stroke();}else rect(x+16,y-6,4,31,'#9bb1a0');}
 if(e.hp<e.maxHP||e.type==='boss'){rect(x-e.r,y-e.r-23,e.r*2,4,'#161b16');rect(x-e.r,y-e.r-23,e.r*2*Math.max(0,e.hp/e.maxHP),4,e.type==='boss'?'#e3a46d':'#afc890');}}
function drawPlayer(){const p=run.player;if(p.invuln>0&&Math.floor(elapsed*14)%2===0)return;const x=p.x,y=p.y,w=weapon(run.weapon);circle(x,y+20,17,'#0007');rect(x-12,y-3,24,27,run.class==='mage'?'#7987ad':run.class==='ranger'?'#70966c':'#879d9c');rect(x-10,y-21,20,19,'#d6b892');rect(x-13,y-23,26,9,'#284d3e');rect(x-14,y,7,19,'#b3c8a3');rect(x+8,y,7,19,'#b3c8a3');const walk=Math.sin(elapsed*12)*(keys.size||Math.hypot(stick.x,stick.y)>.1?4:0);rect(x-9,y+23,7,10+walk,'#3d4d3b');rect(x+3,y+23,7,10-walk,'#3d4d3b');rect(x-5,y-13,3,3,'#2c3123');rect(x+4,y-13,3,3,'#2c3123');ctx.save();ctx.translate(x+p.dx*18,y+p.dy*18);ctx.rotate(Math.atan2(p.dy,p.dx)+Math.PI/2);rect(-2,-24,4,30,w.color);rect(-7,3,14,4,'#c8aa67');if(w.type==='staff')circle(0,-22,7,w.color);if(w.type==='bow'){ctx.strokeStyle=w.color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-7,15,-1.3,1.3);ctx.stroke();}ctx.restore();if(p.dashCD>0){ctx.strokeStyle='#80aa8b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y+4,28,-Math.PI/2,-Math.PI/2+(1-p.dashCD/1.3)*Math.PI*2);ctx.stroke();}}
function render(dt){ctx.save();if(shake>0){ctx.translate(rand(-shake,shake),rand(-shake,shake));shake=Math.max(0,shake-dt*35);}drawRoom(room(),run?.floor||1);if(run){const actors=[...room().enemies.filter(e=>e.hp>0).map(e=>({y:e.y,draw:()=>drawEnemy(e)})),{y:run.player.y,draw:drawPlayer}];actors.sort((a,b)=>a.y-b.y).forEach(a=>a.draw());}for(const b of projectiles){circle(b.x,b.y,b.enemy?5:6,b.color);circle(b.x-b.vx*.012,b.y-b.vy*.012,3,b.color+'77');}if(swing){swing.life-=mode==='play'?dt:0;ctx.strokeStyle=swing.color;ctx.lineWidth=7;ctx.beginPath();ctx.arc(swing.x,swing.y,swing.range*.85,swing.a-1.2,swing.a+1.2);ctx.stroke();if(swing.life<=0)swing=null;}for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.x+=f.vx*dt;f.y+=f.vy*dt;f.life-=dt;ctx.globalAlpha=Math.max(0,Math.min(1,f.life*3));rect(f.x,f.y,4,4,f.color);if(f.life<=0)fx.splice(i,1);}ctx.globalAlpha=1;ctx.font='bold 17px monospace';ctx.textAlign='center';for(let i=texts.length-1;i>=0;i--){const t=texts[i];t.y-=30*dt;t.life-=dt;ctx.fillStyle=t.color;ctx.globalAlpha=Math.max(0,t.life*1.8);ctx.fillText(t.value,t.x,t.y);if(t.life<=0)texts.splice(i,1);}ctx.globalAlpha=1;const v=ctx.createRadialGradient(W/2,H/2,160,W/2,H/2,580);v.addColorStop(0,'#02080400');v.addColorStop(1,'#02080499');ctx.fillStyle=v;ctx.fillRect(0,0,W,H);ctx.restore();}
function frame(t){const dt=Math.min((t-last)/1000||.016,.035);last=t;elapsed+=dt;update(dt);render(dt);if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('visible');}requestAnimationFrame(frame);}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k)&&mode==='play')e.preventDefault();if(e.repeat)return;if(k==='escape'||k==='p'){pause();return;}if(k==='i'){if(mode==='gear')resume();else gear();return;}if(mode!=='play')return;keys.add(k);if(k==='e')interact();if(k==='q')heal();if(k==='shift')dash();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();attacking=false;if(mode==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play')pause();});window.addEventListener('pagehide',save);
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!run)return;const b=canvas.getBoundingClientRect(),dx=(e.clientX-b.left)*W/b.width-run.player.x,dy=(e.clientY-b.top)*H/b.height-run.player.y;const n=Math.hypot(dx,dy)||1;aim={x:dx/n,y:dy/n};mouseAim=true;});canvas.addEventListener('pointerdown',e=>{if(mode==='play'){canvas.focus();if(e.pointerType==='touch'){mouseAim=false;attack();}else{attacking=true;canvas.setPointerCapture(e.pointerId);}}});canvas.addEventListener('pointerup',()=>attacking=false);canvas.addEventListener('pointercancel',()=>attacking=false);canvas.addEventListener('pointerleave',()=>{mouseAim=false;attacking=false;});
let stickPointer=null;function updateStick(e){const b=$('stick').getBoundingClientRect(),dx=e.clientX-b.left-b.width/2,dy=e.clientY-b.top-b.height/2,n=Math.hypot(dx,dy),max=35;stick={x:dx/Math.max(n,max),y:dy/Math.max(n,max)};$('stick-thumb').style.transform=`translate(${stick.x*max}px,${stick.y*max}px)`;mouseAim=false;}
$('stick').onpointerdown=e=>{if(mode!=='play')return;stickPointer=e.pointerId;$('stick').setPointerCapture(e.pointerId);updateStick(e);};$('stick').onpointermove=e=>{if(e.pointerId===stickPointer)updateStick(e);};function releaseStick(){stickPointer=null;stick={x:0,y:0};$('stick-thumb').style.transform='';}$('stick').onpointerup=releaseStick;$('stick').onpointercancel=releaseStick;
$('touch-attack').onpointerdown=e=>{e.preventDefault();mouseAim=false;attacking=true;attack();$('touch-attack').setPointerCapture(e.pointerId);};$('touch-attack').onpointerup=()=>attacking=false;$('touch-attack').onpointercancel=()=>attacking=false;$('touch-dash').onclick=dash;$('touch-heal').onclick=heal;$('touch-use').onclick=interact;$('pause').onclick=pause;$('bag').onclick=gear;$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';if(sound)beep(650,.08);};
title();sync();requestAnimationFrame(frame);
})();
